/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import twitter.Post;
import twitter.Twitter;
import twitter.User;

/**
 *
 * @author group7
 */
public class Profile extends javax.swing.JFrame {

    private User userToShow;
    private User loggedUser;
    public static String Profilepostowner; // for post delete button 
    
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Profile (User userToShow, User loggedUser)
    {
        this.userToShow = userToShow;
        this.loggedUser = loggedUser;
        initComponents();
        this.accSettingsBtn.setVisible(false);
        this.setLocationRelativeTo(null);
        setProfilePic();
        setBio(); 
        setNumbers();
        setPostsList();
        checkIfOwnProfile();
        setFollowStatus();
        
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profilePicLabel2 = new javax.swing.JLabel();
        Profile_Handle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accSettingsBtn = new javax.swing.JButton();
        Bio_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        NumberOfPosts = new javax.swing.JLabel();
        FollowerNumbers = new javax.swing.JLabel();
        FollowingsNumber = new javax.swing.JLabel();
        FollowUnfollow = new javax.swing.JToggleButton();
        NumberOfPosts1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Profile_Handle.setText("Profile-Handle");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Posts");

        accSettingsBtn.setText("Account Settings");
        accSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accSettingsBtnActionPerformed(evt);
            }
        });

        Bio_TextField.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Bio");

        jButton2.setText("ShowFollowers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ShowFollowings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        NumberOfPosts.setText("NPosts");

        FollowerNumbers.setText("FollowersNumber");

        FollowingsNumber.setText("FollowingsNumber");

        FollowUnfollow.setText("Follow");
        FollowUnfollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowUnfollowActionPerformed(evt);
            }
        });

        NumberOfPosts1.setText("Posts");

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profile_Handle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(profilePicLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(181, 181, 181)
                                                .addComponent(Bio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(314, 314, 314)
                                                .addComponent(jLabel2)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(104, 104, 104)
                                            .addComponent(FollowUnfollow)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(accSettingsBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton4)
                                            .addGap(37, 37, 37))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(157, 157, 157)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(NumberOfPosts1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberOfPosts)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FollowerNumbers)
                                .addComponent(FollowingsNumber, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilePicLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile_Handle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accSettingsBtn)
                            .addComponent(jButton4)
                            .addComponent(FollowUnfollow))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumberOfPosts1)
                            .addComponent(NumberOfPosts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FollowerNumbers))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(FollowingsNumber))
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Reload Home Page and Dispose Profile JFrame
        Home home = new Home(loggedUser);
        home.setVisible(true);
        Twitter.openedHomeFrames.add(home);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void accSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accSettingsBtnActionPerformed
        //Reload Account Setting JFrame and dispose Profile JFrame 
        this.dispose();
        AccountSettings Acc = new AccountSettings(loggedUser);
        Acc.setVisible(true);
    }//GEN-LAST:event_accSettingsBtnActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // Show post if the user Double clicked a post in the JList 
        if (evt.getClickCount() == 2) 
        {
            ArrayList <Post> postList = userToShow.getUserPosts();
            Post selectedPost = postList.get(jList2.getSelectedIndex());
            ShowPost showPost = new ShowPost(selectedPost,loggedUser);
            showPost.setVisible(true);
            
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void FollowUnfollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowUnfollowActionPerformed
        // toggled button is toggled if the logged in user follows the owned of the profile 
        if(FollowUnfollow.isSelected())
        {
            loggedUser.addFollowing(userToShow);
            userToShow.addFollower(loggedUser);
            // change the decoration 
            FollowUnfollow.setText("Following");
            FollowUnfollow.setBackground(Color.YELLOW);
            FollowUnfollow.setForeground(Color.BLACK);      
        }
        else // else keep it lame 
        {
            loggedUser.removeFollowing(userToShow);
            userToShow.removeFollower(loggedUser);
            FollowUnfollow.setText("Follow");
            FollowUnfollow.setBackground(Color.WHITE);
            FollowUnfollow.setForeground(Color.BLACK);
        }
        setNumbers();
    }//GEN-LAST:event_FollowUnfollowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Load Jframe of Show Followers 
        ShowFollowers f = new ShowFollowers(userToShow,loggedUser); 
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  // Load Jframe of Show Followings which show the user that follows logged in user  
        ShowFollowings f = new ShowFollowings(userToShow,loggedUser) ; 
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    private void setProfilePic() // Set the profile picture with the avatar in the path 
    {
        ImageIcon profilePic = new ImageIcon(userToShow.getAvatarPath());
        Image image = profilePic.getImage(); // transform it 
        Image scaledProfilePic = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        profilePic = new ImageIcon(scaledProfilePic);  // transform it back
        profilePicLabel2.setIcon(profilePic);
    }
    private void setBio()// change the bio 
    {
        Bio_TextField.setText(userToShow.getBio());
    }
    
    private void setNumbers() // Reload numbers 
    {
        NumberOfPosts.setText(String.valueOf(userToShow.getNumOfPosts()));
        FollowerNumbers.setText(String.valueOf(userToShow.getFollowers().size()));
        FollowingsNumber.setText(String.valueOf(userToShow.getFollowings().size()));
        Profile_Handle.setText(userToShow.getHandle());
    }
    
    private void setPostsList() // get all the post by the current user and display them in the JList 
    {
        ArrayList <Post> posts = userToShow.getUserPosts();
        String [] postsBodies = new String [posts.size()];
        for(int i=0;i<posts.size();i++)
        {
            postsBodies[i]=posts.get(i).getBody();
        }
        jList2 = new javax.swing.JList<>(postsBodies);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = postsBodies;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jScrollPane3.setViewportView(jList2);

    }
    
    // check if its his profile, Usertoshow is an object of type User that came here as a parameter in the Profile constuctor
    private void checkIfOwnProfile()
    {
        if(loggedUser.equals(userToShow))
        {
            FollowUnfollow.setVisible(false);
            accSettingsBtn.setVisible(true);
        }
    }
    
    private void setFollowStatus() // set the following button 
    {
        if(loggedUser.getFollowings().contains(userToShow))
        {
            FollowUnfollow.setSelected(true);
            FollowUnfollow.setText("Following");
            FollowUnfollow.setBackground(Color.YELLOW);
            FollowUnfollow.setForeground(Color.BLACK);
        }
        else
        {
            FollowUnfollow.setSelected(false);
            FollowUnfollow.setText("Follow");
            FollowUnfollow.setBackground(Color.WHITE);
            FollowUnfollow.setForeground(Color.BLACK);
        }
    }
    
    private void refresh()
    {
        this.dispose();
        Profile pf = new Profile(userToShow, loggedUser);
        pf.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bio_TextField;
    private javax.swing.JToggleButton FollowUnfollow;
    private javax.swing.JLabel FollowerNumbers;
    private javax.swing.JLabel FollowingsNumber;
    private javax.swing.JLabel NumberOfPosts;
    private javax.swing.JLabel NumberOfPosts1;
    private javax.swing.JLabel Profile_Handle;
    private javax.swing.JButton accSettingsBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel profilePicLabel2;
    // End of variables declaration//GEN-END:variables
}
