/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.db4o.ObjectSet;
import java.awt.Frame;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import twitter.Hashtag;
import twitter.Post;
import twitter.Repost;
import twitter.User;

/**
 *
 * @author group7
 */
public class ShowPostsWithHashtag extends javax.swing.JFrame {

    public Hashtag selectedHashtag;
    private User loggedUser;
    /**
     * Creates new form ShowPost
     */
    public ShowPostsWithHashtag() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public ShowPostsWithHashtag(Hashtag selectedHashtag, User loggedUser) {
        this.loggedUser = loggedUser;
        this.selectedHashtag = selectedHashtag;
        initComponents();
        this.setLocationRelativeTo(null);
        setHashTagsList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        postsWithTheHashtagList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Post");

        postsWithTheHashtagList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        postsWithTheHashtagList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postsWithTheHashtagListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(postsWithTheHashtagList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postsWithTheHashtagListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postsWithTheHashtagListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) 
        {
            ArrayList <Post> posts = new ArrayList<>(selectedHashtag.getPostsList());
            Post selectedPost = posts.get(postsWithTheHashtagList.getSelectedIndex());
            ShowPost showPost = new ShowPost(selectedPost,loggedUser);
            showPost.checkIfOwnPost() ; // check if the selected post can be deleted by this user 
            showPost.setVisible(true);
        }
    }//GEN-LAST:event_postsWithTheHashtagListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPostsWithHashtag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPostsWithHashtag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPostsWithHashtag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPostsWithHashtag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPostsWithHashtag().setVisible(true);
            }
        });
    }
    
    private void setHashTagsList()
    {
        List<Post> hashtagsList = new ArrayList<>(selectedHashtag.getPostsList());
        String [] posts = new String [hashtagsList.size()];
        for(int i=0;i<hashtagsList.size();i++)
        {
            posts[i]=hashtagsList.get(i).getBody();
        }
        postsWithTheHashtagList = new javax.swing.JList<>(posts);

        postsWithTheHashtagList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = posts;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            
        });
        postsWithTheHashtagList.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            postsWithTheHashtagListMouseClicked(evt);
        }
        });
        jScrollPane2.setViewportView(postsWithTheHashtagList);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> postsWithTheHashtagList;
    // End of variables declaration//GEN-END:variables
}
