/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.db4o.ObjectSet;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import twitter.Notification;
import twitter.Post;
import twitter.Reply;
import twitter.Repost;
import twitter.Twitter;
import twitter.User;

/**
 *
 * @author group7
 */
public class ShowPost extends javax.swing.JFrame {

    private Post selectedPost;
    private User loggedUser;
    /**
     * Creates new form ShowPost
     */
    public ShowPost() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public ShowPost(Post selectedPost, User loggedUser) {
        this.loggedUser = loggedUser;
        this.selectedPost = selectedPost;        
        initComponents();
        this.setLocationRelativeTo(null);
        setThings();
        setProfilePic();
        toggleButtons();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posterAvatarLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        postArea = new javax.swing.JTextArea();
        handleLabel = new javax.swing.JLabel();
        numOfReposts = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numOfLikes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numOfReplies = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        DeletePost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Post");

        posterAvatarLabel.setText("PosterAvatar");
        posterAvatarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posterAvatarLabelMouseClicked(evt);
            }
        });

        postArea.setEditable(false);
        postArea.setColumns(20);
        postArea.setRows(5);
        jScrollPane1.setViewportView(postArea);

        handleLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        handleLabel.setText("Handle");
        handleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleLabelMouseClicked(evt);
            }
        });

        numOfReposts.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        numOfReposts.setText("#ofReposts");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Reposts");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Likes");

        numOfLikes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        numOfLikes.setText("#ofLikes");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Replies");

        numOfReplies.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        numOfReplies.setText("#ofReplies");

        jToggleButton1.setBackground(new java.awt.Color(204, 0, 0));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Like");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(0, 0, 204));
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Repost");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("Reply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DeletePost.setText("Delete");
        DeletePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posterAvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(numOfReposts))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(numOfLikes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(numOfReplies))
                                .addGap(0, 275, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(handleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeletePost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posterAvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numOfReposts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numOfReplies)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numOfLikes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(handleLabel)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jButton2)
                    .addComponent(DeletePost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posterAvatarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterAvatarLabelMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(selectedPost.getPoster(), loggedUser);
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_posterAvatarLabelMouseClicked

    private void handleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleLabelMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(selectedPost.getPoster(), loggedUser);
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_handleLabelMouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton2.isSelected())
        {
            Repost newRepost = new Repost(selectedPost, loggedUser);
            jToggleButton2.setText("Reposted");
        }
        else
        {
            selectedPost.removeRepost(loggedUser);
            jToggleButton2.setText("Repost");

        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            selectedPost.addLike(loggedUser);
            jToggleButton1.setText("Liked");
            setNumbers();
        }
        else
        {
            selectedPost.removeLike(loggedUser);
            jToggleButton1.setText("Like");
            setNumbers();
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void DeletePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePostActionPerformed
        // TODO add your handling code here:
        Post.DeletePostFromDB(selectedPost);
//        loggedUser.decrementNumOfPosts();
        this.dispose(); 
        Frame[] Al = JFrame.getFrames();
        for (int i = 0; i < Al.length; i++) {
            Al[i].dispose();
        }
        Home h = new Home(loggedUser); 
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        Twitter.openedHomeFrames.add(h);

    }//GEN-LAST:event_DeletePostActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ShowReplies SR = new ShowReplies(selectedPost, loggedUser); 
        SR.setVisible(true);
        SR.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPost().setVisible(true);
            }
        });
    }
    
    private void setThings()
    {
        handleLabel.setText(selectedPost.getPoster().getHandle());
        numOfLikes.setText(String.valueOf(selectedPost.getLikes().size()));
        numOfReplies.setText(String.valueOf(selectedPost.getReplies().size()));
        numOfReposts.setText(String.valueOf(selectedPost.getReposts().size()));
        postArea.setText(selectedPost.getBody());
    }
    
    private void setNumbers()
    {
        numOfLikes.setText(String.valueOf(selectedPost.getLikes().size()));
        numOfReplies.setText(String.valueOf(selectedPost.getReplies().size()));
        numOfReposts.setText(String.valueOf(selectedPost.getReposts().size()));
    }
    
    private void setProfilePic()
    {
        ImageIcon profilePic = new ImageIcon(selectedPost.getPoster().getAvatarPath());
        Image image = profilePic.getImage();
        Image scaledProfilePic = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH); // scale the image  
        profilePic = new ImageIcon(scaledProfilePic); 
        posterAvatarLabel.setIcon(profilePic);
    }
    
    private void toggleButtons()
    {
        if(selectedPost.getLikes().contains(loggedUser))
        {
            jToggleButton1.setText("Liked");
            jToggleButton1.setSelected(true);
        }
        if(selectedPost.getReposts().contains(loggedUser))
        {
            jToggleButton2.setText("Reposted");
            jToggleButton2.setSelected(true);
        }
    }
     
    // check if the selected post can be deleted by this user 
    public void checkIfOwnPost() 
    {
        if(selectedPost.getPoster().getName().equals(loggedUser.getName()))
        {
            DeletePost.setVisible(true);
        }
        else  DeletePost.setVisible(false);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletePost;
    public javax.swing.JLabel handleLabel;
    private javax.swing.JButton jButton2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JLabel numOfLikes;
    public javax.swing.JLabel numOfReplies;
    public javax.swing.JLabel numOfReposts;
    private javax.swing.JTextArea postArea;
    private javax.swing.JLabel posterAvatarLabel;
    // End of variables declaration//GEN-END:variables
}
